name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  ci:
    name: Continuous Integration on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install devbox
        uses: jetify-com/devbox-install-action@a0d2d53632934ae004f878c840055956d9f741b0 # v0.14.0

      - name: Set up uv
        run: devbox run -- uv sync --locked

      - name: Check formatting
        run: devbox run -- uv run ruff format --check

      - name: Lint
        run: devbox run -- uv run ruff check

      - name: Type check
        run: devbox run -- uv run mypy .

      - name: Run tests
        run: devbox run -- uv run pytest --cov=src/factortool --cov-report=term-missing

  # Devbox is not currently natively supported on Windows (and may never be), so we use uv directly here.
  ci-windows:
    name: Continuous Integration on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
        with:
          version: "0.10.2"

      - name: Set up uv
        run: uv sync --locked

      - name: Check formatting
        run: uv run ruff format --check

      - name: Lint
        run: uv run ruff check

      - name: Type check
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest --cov=src/factortool --cov-report=term-missing
